Repository DesktopGooseUnofficial/ResourceHub, pull requests merged in 2020-04, with the labels that each got.

#95 Update hatgoos.md
  mods/hatgoos.md
Labels: mods, size/XS

#96 Added my own clean notepad collection!
  README.md
Labels: size/XS

#97 new notepad pack
  README.md
Labels: size/XS

#98 Got rid of .zip
  README.md
Labels: size/XS

#99 Create GamerBoi153's Notepad Pack
  README.md
  notepads/GamerBoi153sNotepad.md
Labels: size/S

#100 fixed link
  notepads/GamerBoi153sNotepad.md
Labels: size/XS

#101 Added Description
  notepads/GamerBoi153sNotepad.md
Labels: size/XS

#103 New tutorial, .zip fix and credit
  README.md
  notepads/GamerBoi153sNotepad.md
Labels: size/XS

#104 How to close desktop goose tutorial, link to beta launcher, link to CONTRIBUTING.md
  README.md
  tutorials/StopDesktopGoose.md
Labels: size/S, tutorials

#105 wayyyy more stuff in FAQ and not just mod help
  README.md
Labels: size/M, tutorials

#108 Disclaimer
  README.md
Labels: size/XS

#109 updating portalgoos to v1.1
  mods/PortalGoos.md
Labels: mods, size/XS
